#  задание урока 1. PyTorch

In [88]:
import torch

In [89]:
import numpy as np

In [90]:
# Создайте случайный FloatTensor размера 3x4x5

x = torch.randn(3, 4, 5).type(torch.float32)
print("x :\n%s\n" % x)

x :
tensor([[[-0.1666,  0.7059, -1.7250, -0.8070, -0.6664],
         [-1.2984,  1.0890,  0.7242, -0.6391, -0.7070],
         [-0.2755, -1.3074,  0.1582, -0.0057,  1.2881],
         [-0.8884, -1.1437, -1.8264, -2.2973,  0.1239]],

        [[-1.1586, -0.3523, -0.7035, -0.0913,  0.7298],
         [-0.9413, -0.7131,  0.5364,  0.8157,  0.0676],
         [ 1.4116,  0.3667, -0.2626, -0.3809, -0.6749],
         [ 0.4721,  1.3176, -0.9188, -0.2177,  0.3903]],

        [[-0.3244,  1.0759, -0.2021,  0.2730,  0.1046],
         [-0.0141,  1.4298,  2.1902, -1.2672, -0.8386],
         [ 1.3650,  0.5416,  0.4541, -0.0828,  0.7294],
         [ 0.6432, -0.3901,  0.3418, -0.4855,  0.1689]]])



In [91]:
# Выведите его форму (shape)

print("x размеры : %s\n" % (x.shape,))

x размеры : torch.Size([3, 4, 5])



In [92]:
# Приведите его к форме 6 X 10

x.resize_(6, 10)
print("x размеры : %s\n" % (x.shape,))

x размеры : torch.Size([6, 10])



In [93]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x.resize_(3, 4, 5)
print("x размеры : %s\n" % (x.shape,))

x размеры : torch.Size([3, 4, 5])



In [94]:
vec = torch.FloatTensor([1, 4, 2, 2, 1])

In [95]:
x * vec

tensor([[[-0.1666,  2.8235, -3.4500, -1.6140, -0.6664],
         [-1.2984,  4.3559,  1.4483, -1.2782, -0.7070],
         [-0.2755, -5.2297,  0.3164, -0.0113,  1.2881],
         [-0.8884, -4.5747, -3.6528, -4.5947,  0.1239]],

        [[-1.1586, -1.4092, -1.4071, -0.1825,  0.7298],
         [-0.9413, -2.8524,  1.0729,  1.6315,  0.0676],
         [ 1.4116,  1.4669, -0.5251, -0.7618, -0.6749],
         [ 0.4721,  5.2703, -1.8376, -0.4354,  0.3903]],

        [[-0.3244,  4.3038, -0.4042,  0.5460,  0.1046],
         [-0.0141,  5.7193,  4.3805, -2.5344, -0.8386],
         [ 1.3650,  2.1662,  0.9082, -0.1656,  0.7294],
         [ 0.6432, -1.5602,  0.6836, -0.9711,  0.1689]]])

In [96]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [97]:
x.resize_(6, 10)
torch.matmul(x, x.transpose(0,1)).size()

torch.Size([6, 6])

In [98]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [99]:
from torch.autograd import Variable

In [100]:
def print_tens_info(tensor):
    print("X :\n%s\n" % tensor)
    print("X количество измерений:\n%s\n" % tensor.dim())
    print("X размеры : ",  tensor.size())
    print("X тип : %s\n" % (tensor.type()))


In [101]:
x = Variable(torch.FloatTensor([1, 0.5, 2]), requires_grad = True)
z = Variable(torch.ones(3), requires_grad = True)
t = Variable(torch.ones(3), requires_grad = True)

In [102]:
y = x**3 + z - 75*t
print_tens_info(y)

X :
tensor([-73.0000, -73.8750, -66.0000], grad_fn=<SubBackward0>)

X количество измерений:
1

X размеры :  torch.Size([3])
X тип : torch.FloatTensor



In [103]:
y.backward(torch.ones(3))

In [104]:
print("Производная в точке x = (1, 0.5, 2) : %s\n" % (x.grad))

Производная в точке x = (1, 0.5, 2) : tensor([ 3.0000,  0.7500, 12.0000])



In [105]:
# Создайте единичный тензор размера 5x6

x = torch.ones(5,6)
print("X :\n%s\n" % x)
print("X размеры : %s\n" % (x.shape,))
print("X тип : %s\n" % (type(x)))

X :
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

X размеры : torch.Size([5, 6])

X тип : <class 'torch.Tensor'>



In [106]:
# Переведите его в формат numpy

x = x.numpy()
print("X :\n%s\n" % x)
print("X размеры : %s\n" % (x.shape,))
print("X тип : %s\n" % (type(x)))

X :
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

X размеры : (5, 6)

X тип : <class 'numpy.ndarray'>

